//ARITHMETIC OPERATORS
/* (+ - / * % ) are the arithmetic operators
12%2=0
12**2=12*12=144*/


/*COMPARISON OPERATOR
== --> IT IS NOT STRICT COMPARISON, USE TO COMPARE BOTH SIDES, IT DOES NOT COMPARE THE DATA TYPES
=== --> USED TO COMPARE BOTH SIDES ON THE BASIS OF DATA TYPES
!= --> NOT STRICT COMPARISON, DOES NOT COMPARE ON THE BASIS OF DATA TYPES
!== --> IT COMPARES BOTH SIDES ON THE BASIS OF DATA TYPES
>= -->LESS THAN OR EQUAL TO 
<= ---> GREATER THAN OR EQUAL TO
<  ---> GREATER THAN
> ----> LESSER THAN
12==13---->FALSE
12 == '12' --->IT WILL COME TRUE WEREAS IT SHOULD BE FALSE
12 === '12' --->NOW IT WILL COME FALSE
12!=13 --->IS 12 NOT EQUAL TO 13? TRUE 
"HARSH" != "HARSHITA" ----> TRUE
12 != '12'--->FALSE
12!=='12'--->TRUE */








/*ASSIGNMENT OPERATORS
=
+=
-=
*=
/=
%=
let a = 23; 
a += 3 --->a+3 = 15
a-=11 -->a-11 = 4
a*=2 ---->a*2=8
a/=2----->a/2=4
a%=3 ----->a%3=1










/*LOGICAL OPERATORS
&& -->DONO CONDITIONS: TRUE, FINAL ANSWER:TRUE
|| --> KOI BHI EK CONDITION:TRUE, FINAL ANSWER: TURE
!  ---> TRUE VALUE FALSE HOJAYEGI, FALSE VALUE TRUE HOJAYEGI
*/


/*unary
++a
a++
a--
--a
*/



/*ternary 
12>13 ? console.log("true"):console.log("false")
*/






/*TYPEOF, INSTANCEOF

*****QUIRCKS OF JAVASCRIPT******
typeof null ----> object
typeof array----> object
typeof NaN----> Number





//INSTANCEOF
IT IS USED IN THE CASE OF REFERENCE VALUES LIKE ARRAYS, OBJECTS AND FUNCTIONS




